const profileData = [
    {
      ID: "12351",
      Photo: "photo_url7",
      First_Name: "Eve",
      Last_Name: "White",
      Gender: "Female",
      Age: "29",
      Role: "Admin",
      DOB: "1991-07-07",
      Email: "eve.white@example.com",
      verification_Email: "eve.white@verify.com",
      Phone: "123-456-7896",
      CreatedAt: "2014-01-01",
      Updated_At: "2015-01-01",
      Website: "www.evewhite.com",
      Username: "evewhite",
      Matched: "Yes",
      OTP: "723456",
      Email_OTP: "304321",
      User_Onboarding_Stage: "Completed",
      Document_Verification: "Verified",
    },
    {
      ID: "12351",
      Photo: "photo_url7",
      First_Name: "Eve",
      Last_Name: "White",
      Gender: "Female",
      Age: "29",
      Role: "Admin",
      DOB: "1991-07-07",
      Email: "eve.white@example.com",
      verification_Email: "eve.white@verify.com",
      Phone: "123-456-7896",
      CreatedAt: "2014-01-01",
      Updated_At: "2015-01-01",
      website: "www.evewhite.com",
      Username: "evewhite",
      Matched: "Yes",
      OTP: "723456",
      Email_OTP: "304321",
      User_Onboarding_Stage: "Completed",
      Document_Verification: "Verified",
    },
    {
      ID: "12351",
      Photo: "photo_url7",
      First_Name: "Eve",
      Last_Name: "White",
      Gender: "Female",
      Age: "29",
      Role: "Admin",
      DOB: "1991-07-07",
      Email: "eve.white@example.com",
      verification_Email: "eve.white@verify.com",
      Phone: "123-456-7896",
      CreatedAt: "2014-01-01",
      Updated_At: "2015-01-01",
      website: "www.evewhite.com",
      Username: "evewhite",
      Matched: "Yes",
      OTP: "723456",
      Email_OTP: "304321",
      User_Onboarding_Stage: "Completed",
      Document_Verification: "Verified",
    },
    {
      ID: "12351",
      Photo: "photo_url7",
      First_Name: "Eve",
      Last_Name: "White",
      Gender: "Female",
      Age: "29",
      Role: "Admin",
      DOB: "1991-07-07",
      Email: "eve.white@example.com",
      verification_Email: "eve.white@verify.com",
      Phone: "123-456-7896",
      CreatedAt: "2014-01-01",
      Updated_At: "2015-01-01",
      website: "www.evewhite.com",
      Username: "evewhite",
      Matched: "Yes",
      OTP: "723456",
      Email_OTP: "304321",
      User_Onboarding_Stage: "Completed",
      Document_Verification: "Verified",
    },
    {
      ID: "12351",
      Photo: "photo_url7",
      First_Name: "Eve",
      Last_Name: "White",
      Gender: "Female",
      Age: "29",
      Role: "Admin",
      DOB: "1991-07-07",
      Email: "eve.white@example.com",
      verification_Email: "eve.white@verify.com",
      Phone: "123-456-7896",
      CreatedAt: "2014-01-01",
      Updated_At: "2015-01-01",
      website: "www.evewhite.com",
      Username: "evewhite",
      Matched: "Yes",
      OTP: "723456",
      Email_OTP: "304321",
      User_Onboarding_Stage: "Completed",
      Document_Verification: "Verified",
    },
    {
      ID: "12351",
      Photo: "photo_url7",
      First_Name: "Eve",
      Last_Name: "White",
      Gender: "Female",
      Age: "29",
      Role: "Admin",
      DOB: "1991-07-07",
      Email: "eve.white@example.com",
      verification_Email: "eve.white@verify.com",
      Phone: "123-456-7896",
      CreatedAt: "2014-01-01",
      Updated_At: "2015-01-01",
      website: "www.evewhite.com",
      Username: "evewhite",
      Matched: "Yes",
      OTP: "723456",
      Email_OTP: "304321",
      User_Onboarding_Stage: "Completed",
      Document_Verification: "Verified",
    },
    {
      ID: "12351",
      Photo: "photo_url7",
      First_Name: "Eve",
      Last_Name: "White",
      Gender: "Female",
      Age: "29",
      Role: "Admin",
      DOB: "1991-07-07",
      Email: "eve.white@example.com",
      verification_Email: "eve.white@verify.com",
      Phone: "123-456-7896",
      CreatedAt: "2014-01-01",
      Updated_At: "2015-01-01",
      website: "www.evewhite.com",
      Username: "evewhite",
      Matched: "Yes",
      OTP: "723456",
      Email_OTP: "304321",
      User_Onboarding_Stage: "Completed",
      Document_Verification: "Verified",
    }
  ];
  
  export default profileData;
  